# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2

Rails:
  Enabled: true

Rails/ActionControllerFlashBeforeRender:
  Enabled: true
Rails/ActionControllerTestCase:
  Enabled: true
Rails/ActionOrder:
  Enabled: true
Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/ActiveSupportOnLoad:
  Enabled: true
Rails/AddColumnIndex:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/AttributeDefaultBlockValue:
  Enabled: true
Rails/CompactBlank:
  Enabled: true
Rails/DangerousColumnNames:
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: true
Rails/DotSeparatedKeys:
  Enabled: true
Rails/DuplicateAssociation:
  Enabled: true
Rails/DuplicateScope:
  Enabled: true
Rails/DurationArithmetic:
  Enabled: true
Rails/EagerEvaluationLogMessage:
  Enabled: true
Rails/EnumSyntax:
  Enabled: true
Rails/EnvLocal:
  Enabled: true
Rails/ExpandedDateRange:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/FreezeTime:
  Enabled: true
Rails/I18nLazyLookup:
  Enabled: true
Rails/I18nLocaleAssignment:
  Enabled: true
Rails/I18nLocaleTexts:
  Enabled: true
Rails/IgnoredColumnsAssignment:
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/MigrationClassName:
  Enabled: true
Rails/MultipleRoutePaths:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RedundantActiveRecordAllMethod:
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true
Rails/RedundantTravelBack:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ResponseParsedBody:
  Enabled: true
Rails/RootJoinChain:
  Enabled: true
Rails/RootPathnameMethods:
  Enabled: true
Rails/RootPublicPath:
  Enabled: true
Rails/SelectMap:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/SquishedSQLHeredocs:
  Enabled: true
Rails/StripHeredoc:
  Enabled: true
Rails/StrongParametersExpect:
  Enabled: true
Rails/ThreeStateBooleanColumn:
  Enabled: true
Rails/TimeZoneAssignment:
  Enabled: true
Rails/ToFormattedS:
  Enabled: true
Rails/ToSWithArgument:
  Enabled: true
Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true
Rails/TransactionExitStatement:
  Enabled: true
Rails/UnusedRenderContent:
  Enabled: true
Rails/WhereEquals:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Rails/WhereMissing:
  Enabled: true
Rails/WhereNot:
  Enabled: true
Rails/WhereNotWithMultipleConditions:
  Enabled: true
Rails/WhereRange:
  Enabled: true
