default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>

development:
  <<: *default
  database: it_jobs_development

test:
  <<: *default
  database: it_jobs_test

production:
  <<: *default
  database: it_jobs_production
  username: it_jobs
  password: <%= ENV["IT_JOBS_DATABASE_PASSWORD"] %>
